version: '3.8'
services:
  backend:
      build:
        context: .
        dockerfile: Dockerfile
      extra_hosts:
        host.docker.internal: host-gateway
      command: 'python main.py'
      ports:
        - 8001:5000
      volumes:
        - .:/app
      depends_on:
        - db
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: admin
    volumes:
      - .dbdata:/var/lib/postgresql
    ports:
      - 5433:5432